vlib work
vlib riviera

vlib riviera/xilinx_vip
vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v2_0_3
vlib riviera/axi_vip_v1_1_3
vlib riviera/zynq_ultra_ps_e_vip_v1_0_3
vlib riviera/jtag_axi
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_12
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/lib_pkg_v1_0_2
vlib riviera/fifo_generator_v13_2_2
vlib riviera/lib_fifo_v1_0_11
vlib riviera/axi_fifo_mm_s_v4_1_14
vlib riviera/gigantic_mux
vlib riviera/xlconcat_v2_1_1
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/axi_data_fifo_v2_1_16
vlib riviera/axi_register_slice_v2_1_17
vlib riviera/axi_protocol_converter_v2_1_17
vlib riviera/axi_clock_converter_v2_1_16
vlib riviera/blk_mem_gen_v8_4_1
vlib riviera/axi_dwidth_converter_v2_1_17

vmap xilinx_vip riviera/xilinx_vip
vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_3 riviera/axi_protocol_checker_v2_0_3
vmap axi_vip_v1_1_3 riviera/axi_vip_v1_1_3
vmap zynq_ultra_ps_e_vip_v1_0_3 riviera/zynq_ultra_ps_e_vip_v1_0_3
vmap jtag_axi riviera/jtag_axi
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_12 riviera/proc_sys_reset_v5_0_12
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap lib_pkg_v1_0_2 riviera/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_2 riviera/fifo_generator_v13_2_2
vmap lib_fifo_v1_0_11 riviera/lib_fifo_v1_0_11
vmap axi_fifo_mm_s_v4_1_14 riviera/axi_fifo_mm_s_v4_1_14
vmap gigantic_mux riviera/gigantic_mux
vmap xlconcat_v2_1_1 riviera/xlconcat_v2_1_1
vmap generic_baseblocks_v2_1_0 riviera/generic_baseblocks_v2_1_0
vmap axi_data_fifo_v2_1_16 riviera/axi_data_fifo_v2_1_16
vmap axi_register_slice_v2_1_17 riviera/axi_register_slice_v2_1_17
vmap axi_protocol_converter_v2_1_17 riviera/axi_protocol_converter_v2_1_17
vmap axi_clock_converter_v2_1_16 riviera/axi_clock_converter_v2_1_16
vmap blk_mem_gen_v8_4_1 riviera/blk_mem_gen_v8_4_1
vmap axi_dwidth_converter_v2_1_17 riviera/axi_dwidth_converter_v2_1_17

vlog -work xilinx_vip  -sv2k12 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_3  -sv2k12 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_3  -sv2k12 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work zynq_ultra_ps_e_vip_v1_0_3  -sv2k12 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ipshared/bf16/hdl/gcc_core.vhd" \
"../../../bd/design_1/ipshared/bf16/hdl/gcc_customIp.vhd" \
"../../../bd/design_1/ipshared/bf16/hdl/gcc_customIp_M00_AXIS.vhd" \
"../../../bd/design_1/ipshared/bf16/hdl/gcc_customIp_S00_AXI.vhd" \
"../../../bd/design_1/ip/design_1_gcc_customIP_0_1/sim/design_1_gcc_customIP_0_1.vhd" \

vlog -work jtag_axi  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/567c/hdl/jtag_axi_v1_2_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_jtag_axi_0_1/sim/design_1_jtag_axi_0_1.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_rst_ps8_0_99M_1/sim/design_1_rst_ps8_0_99M_1.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_2  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_2 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_2  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_11 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work axi_fifo_mm_s_v4_1_14 -93 \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/99f9/hdl/axi_fifo_mm_s_v4_1_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_fifo_mm_s_0_0/sim/design_1_axi_fifo_mm_s_0_0.vhd" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.vhd" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.vhd" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/sim/bd_f60c_slot_0_aw_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/sim/bd_f60c_slot_0_w_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/sim/bd_f60c_slot_0_b_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/sim/bd_f60c_slot_0_ar_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/sim/bd_f60c_slot_0_r_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_7/sim/bd_f60c_slot_2_aw_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_8/sim/bd_f60c_slot_2_w_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_9/sim/bd_f60c_slot_2_b_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_10/sim/bd_f60c_slot_2_ar_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_11/sim/bd_f60c_slot_2_r_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.vhd" \
"../../../bd/design_1/ip/design_1_vio_0_0/sim/design_1_vio_0_0.vhd" \
"../../../bd/design_1/sim/design_1.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_16  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_17  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_17  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work axi_clock_converter_v2_1_16  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e9a5/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work blk_mem_gen_v8_4_1  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \

vlog -work axi_dwidth_converter_v2_1_17  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/2839/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+../../../../gcc_top.srcs/sources_1/bd/design_1/ipshared/ef07/hdl" "+incdir+C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
"../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

